### ISSUE TITLE
Why do you use Quarkus with Graalvm

### ISSUE THREAD

**Issue by HelloTo4x** [janobono/the-final-nut#1]
Hi, why do you use Quarkus instead of Spring Native, i see Spring Native has large ecosystem with Spring, so we can do it. Can u tell me if you about your purpose when using Quarkus, the pros and cons of Quarkus, thank u so much

**Comment by janobono** [comment]
Hi, the repository was created 2 years ago. Spring Native doesn't exist at the moment of creation. Quarkus is maybe better for somebody who worked with J2EE but here I was looking for a native alternative in Java. We won't use it for a project but a lot of libs are still in preview state so we choose SpringBoot as a final solution.
Really simple comparison is here [github.com/janobono/the-two-nuts-with-chocolate](https://github.com/janobono/the-two-nuts-with-chocolate).
